# Generated by Django 5.0.1 on 2024-02-04 17:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='band',
            name='biography',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='band',
            name='genre',
            field=models.CharField(choices=[('HH', 'Hip Hop'), ('SP', 'Synth Pop'), ('AR', 'Alternative Rock'), ('IR', 'Indie Rock'), ('PO', 'Pop'), ('JA', 'Jazz'), ('BL', 'Blues'), ('CO', 'Country'), ('EL', 'Electronic'), ('TE', 'Techno'), ('CL', 'Classical'), ('RE', 'Reggae'), ('ME', 'Metal'), ('PU', 'Punk'), ('FU', 'Funk'), ('RB', 'R And B'), ('SO', 'Soul'), ('FO', 'Folk'), ('WO', 'World'), ('OT', 'Other')], default='HH', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='band',
            name='official_homepag',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='band',
            name='year_formed',
            field=models.IntegerField(default=2000, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2024)]),
            preserve_default=False,
        ),
    ]
