# Generated by Django 5.0.1 on 2024-02-05 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_listing_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='type',
        ),
    ]
